export type Entry={value:string;weight:number};
export const genres=[{name:'Leftfield electro / dub-techno',min:112,max:132,modes:['Dorian','Minor','Phrygian']},{name:'Ambient / downtempo',min:65,max:100,modes:['Dorian','Major','Lydian','Minor']},{name:'Broken beat / future garage',min:125,max:142,modes:['Minor','Dorian']},{name:'Jungle / drum & bass',min:160,max:176,modes:['Minor','Dorian','Phrygian']},{name:'House / deep house',min:115,max:128,modes:['Minor','Dorian','Mixolydian']},{name:'Experimental hip-hop',min:75,max:100,modes:['Minor','Dorian','Phrygian']},{name:'Synthwave',min:90,max:118,modes:['Minor','Dorian','Major']}];
const weighted=(a:string[])=>a.map(value=>({value,weight:1}));
export const defaultPools:Record<string,Entry[]>={style:weighted(genres.map(g=>g.name)),root:weighted(['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B']),mode:weighted(['Minor','Dorian','Phrygian','Major','Lydian','Mixolydian']),sample:weighted(['One field recording of a mechanical sound','Record a kitchen object','Record water in motion','Record a door, latch, or hinge','Record a short spoken phrase','Record footsteps on an unusual surface']),technique:weighted(['Make the same recording both percussion and a sustained / tonal element','Resample the source three times; use the final generation','Build a playable instrument from your source recording','Use the source forward and reversed in a call-and-response']),instrumentation:weighted(['Max one synth plugin or hardware synth','Samples only; no synth instruments','Max two synth instruments']),arrangement:weighted(['At least one 16-bar section with no kick','Begin with texture; introduce the main groove after 16 bars','Bring the opening motif back in a different form','Include an 8-bar section with only two audible parts']),tracks:weighted(['8','10','12']),length:weighted(['2:30–4:30','2:00–3:30','3:00–5:00']),forbidden:weighted(['No additional restrictions','No premade drum loops','No crash cymbals','No riser presets']),bonus:weighted(['Hide one sound the other participant would recognize as an inside joke','Let a tiny accidental sound become the hook','Hide a rhythmic Morse-code message','Include one second of complete silence','Make the last sound connect to the first'])};
export type Settings={min:number;max:number;range:boolean;excluded:string;pools:Record<string,Entry[]>};
export const defaultSettings:Settings={min:60,max:180,range:false,excluded:'',pools:defaultPools};
export type Submission={status:string;title:string;notes:string;link:string;file:string};
export type Week={id:string;number:number;title:string;deadline:string;locked:boolean;fields:Record<string,string>;submissions:Record<string,Submission>;reactions:Record<string,Record<string,string>>};
export const participants=[{id:'tripp',name:'Tripp'},{id:'may',name:'May'}];
export const blank=():Submission=>({status:'Not Started',title:'',notes:'',link:'',file:''});
export const datePlus=(days:number,from=new Date())=>{const d=new Date(from);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function seed():Week{return {id:'neon-shrine',number:1,title:'NEON SHRINE',deadline:datePlus(7),locked:true,fields:{bpm:'124',key:'A Dorian',style:genres[0].name,sample:defaultPools.sample[0].value,technique:defaultPools.technique[0].value,tracks:'10',instrumentation:defaultPools.instrumentation[0].value,arrangement:defaultPools.arrangement[0].value,length:'2:30–4:30',forbidden:'No additional restrictions',bonus:defaultPools.bonus[0].value},submissions:Object.fromEntries(participants.map(p=>[p.id,blank()])),reactions:{}}}
export const labels:Record<string,string>={style:'Style',bpm:'Tempo',key:'Key / mode',sample:'Required source',technique:'Transformation',instrumentation:'Instruments',tracks:'Mixer track limit',arrangement:'Arrangement',length:'Track length',forbidden:'Forbidden elements',bonus:'Bonus / wildcard'};
function pick(entries:Entry[]){const a=entries.filter(e=>e.weight>0);const total=a.reduce((n,e)=>n+e.weight,0);if(!total)throw Error('Enable at least one choice in every pool.');let n=Math.random()*total;for(const e of a){n-=e.weight;if(n<=0)return e.value}return a[a.length-1].value}
export function availableTempos(s:Settings,g:typeof genres[number]){const excluded=s.excluded.split(',').map(x=>Number(x.trim()));return Array.from({length:g.max-g.min+1},(_,i)=>i+g.min).filter(n=>n>=s.min&&n<=s.max&&!excluded.includes(n))}
function eligible(s:Settings){return s.pools.style.filter(e=>{const g=genres.find(g=>g.name===e.value);return g&&e.weight>0&&availableTempos(s,g).length&&s.pools.mode.some(m=>m.weight>0&&g.modes.includes(m.value))})}
function musical(s:Settings,style:string){const g=genres.find(g=>g.name===style)!;const tempos=availableTempos(s,g);if(!tempos.length)throw Error('This style has no enabled BPMs. Reroll the style or update settings.');const mid=(g.min+g.max)/2;const bpm=Number(pick(tempos.map(t=>({value:String(t),weight:Math.max(1,12-Math.abs(t-mid))}))));const hi=Math.min(bpm+4,...[Math.max(...tempos)]);const range=s.range&&hi>bpm&&Array.from({length:hi-bpm+1},(_,i)=>bpm+i).every(n=>tempos.includes(n));return {bpm:range?`${bpm}–${hi}`:String(bpm),key:`${pick(s.pools.root)} ${pick(s.pools.mode.filter(m=>g.modes.includes(m.value)))}`}}
export function generate(s:Settings,number:number,deadline:string):Week{const styles=eligible(s);if(!styles.length)throw Error('No compatible style, tempo, and mode combination. Broaden your settings.');const style=pick(styles);const fields:Record<string,string>={style,...musical(s,style)};for(const k of Object.keys(labels))if(!(k in fields))fields[k]=pick(s.pools[k]);return {id:crypto.randomUUID(),number,title:`${pick(weighted(['GHOST','VELVET','STATIC','LUNAR','CHROME','MIDNIGHT']))} ${pick(weighted(['GARDEN','CIRCUIT','SIGNAL','TIDE','ROOM','BLOOM']))}`,deadline,locked:false,fields,submissions:Object.fromEntries(participants.map(p=>[p.id,blank()])),reactions:{}}}
export function reroll(w:Week,k:string,s:Settings):Week{if(w.locked)return w;const f={...w.fields};if(k==='style'){f.style=pick(eligible(s));Object.assign(f,musical(s,f.style))}else if(k==='bpm'||k==='key'){f[k]=musical(s,f.style)[k]}else f[k]=pick(s.pools[k]);return {...w,fields:f}}
export function challengeText(w:Week){return `TRACK PACT · WEEK ${w.number}\n${w.title}\nDue ${w.deadline} (end of day)\n\n${Object.entries(labels).map(([k,l])=>`${l}: ${w.fields[k]}${k==='bpm'?' BPM':''}`).join('\n')}\n\nTripp × May — two takes, same rules.`}
